# Generated by Django 4.1.4 on 2023-01-02 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Цель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание цели')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('date_complete', models.DateTimeField(verbose_name='Дата комплита')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список целей',
                'verbose_name_plural': 'Список целей',
                'ordering': ('deadline',),
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Задача')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('date_complete', models.DateTimeField(verbose_name='Дата комплита')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposes.purposes', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Список задач',
                'ordering': ('deadline',),
            },
        ),
    ]
