# Generated by Django 4.1.4 on 2023-01-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purposes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purposes',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата комплита'),
        ),
    ]
